@Wildlife_Sports_Day_Server_HostAddress = http://localhost:5233

POST {{Wildlife_Sports_Day_Server_HostAddress}}/Auth/Email-Code/Send
Content-Type: application/json

{
  "email": "player@example.com"
}

###

POST {{Wildlife_Sports_Day_Server_HostAddress}}/Auth/Email-Code/Verify
Content-Type: application/json

{
  "email": "player@example.com",
  "code": "123456"
}

###
